#!/usr/bin/env bash
#Displays hours from 0 to 12 and min from 1 to 59

hours=0

while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	(( hours++ ))
done
